apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-wars-deployment
spec:
  selector:
    matchLabels:
      app: star-wars
  replicas: 1
  template:
    metadata:
      labels:
        app: star-wars
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: star-wars
          image: starwars-node
          ports:
            - containerPort: 3000
          imagePullPolicy: Never # Image should not be pulled
          volumeMounts:
            - mountPath: "/usr/output"
              name: task-pv-storage
